/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view_IF;

import controller_IF.IgneoFinanzasController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import model_IF.ModeloIgneoFinanzas;

/**
 *
 * @author ignac
 */
public class VentanaPresentacion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPresentacion
     */
    public VentanaPresentacion() {
        initComponents();
        initComponents();
        configurarVentana();
        animarTextoCargando();
        simularCarga();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCargando = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCargando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCargando.setText("Caragando");
        getContentPane().add(lblCargando, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCargando;
    // End of variables declaration//GEN-END:variables
//Mis metodos y variables
    /**
     * Metodo con los ajustes pedidos de la ventana de carga
     */
    private void configurarVentana() {
        setTitle("Bienvenido a Igneo Finanzas");
        setSize(400, 300); // Tamaño fijo
        setLocationRelativeTo(null); // Centrar en pantalla
        setResizable(false);
    }

    /**
     * Metodo que ejcuta la pantalla de carga, la animacion y abre la ventana
     * pricmnipal
     */
    private void simularCarga() {
        Timer timer = new Timer(3000, new ActionListener() { // Timer de 3 segundos
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose(); // Cierra la ventana de carga
                abrirVentanaPrincipal(); // Abre la ventana principal
            }
        });
        timer.setRepeats(false); // Evita que el Timer se ejecute en bucle
        timer.start(); // Inicia el Timer
    }

    /**
     * Metodo para crear el controller y ejecutar todo de ventana principal
     */
    private void abrirVentanaPrincipal() {
        // Crear la ventana principal y el modelo
        VistaInicialgneoFinanzas ventanaPrincipal = new VistaInicialgneoFinanzas();
        ModeloIgneoFinanzas modeloIF = new ModeloIgneoFinanzas();

        // Iniciar el controlador con la vista y el modelo
        new IgneoFinanzasController(ventanaPrincipal, modeloIF);
    }

    /**
     * Metodo opara simular la animacion de caragr con la clase Timer
     */
    private void animarTextoCargando() {
        // Timer para la animación de puntos
        Timer timer = new Timer(500, new ActionListener() { // Cada 500 ms
            int contador = 0;

            @Override
            public void actionPerformed(ActionEvent e) {
                contador = (contador + 1) % 4; // Cambia entre 0, 1, 2, 3
                lblCargando.setText("Cargando" + ".".repeat(contador));
            }
        });
        timer.start();
    }

}
